"""publications_stages_evidence"""

import sqlalchemy as sa
from alembic import op

revision = "1d986a0ded8f"
down_revision = "653671451bb1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "publications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("process_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paragraphs", sa.JSON(), nullable=False),
        sa.Column("documents", sa.JSON(), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confidence", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["process_id"],
            ["processes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id"),
    )
    op.create_index(
        op.f("ix_publications_process_id"), "publications", ["process_id"], unique=False
    )
    op.create_table(
        "changes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("process_id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("old_value", sa.JSON(), nullable=True),
        sa.Column("new_value", sa.JSON(), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["process_id"],
            ["processes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_changes_process_id"), "changes", ["process_id"], unique=False)
    op.create_table(
        "event_evidence",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "source_id", "content_hash"),
    )
    op.create_index(
        op.f("ix_event_evidence_event_id"), "event_evidence", ["event_id"], unique=False
    )
    op.create_table(
        "stages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("process_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("modality", sa.String(length=30), nullable=False),
        sa.Column("population", sa.String(length=30), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("confidence", sa.String(length=20), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("timezone", sa.String(length=40), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["process_id"],
            ["processes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("process_id", "kind", "modality", "population"),
    )
    op.create_index(op.f("ix_stages_process_id"), "stages", ["process_id"], unique=False)
    op.add_column(
        "events",
        sa.Column("confidence", sa.String(length=20), server_default="CONFIRMED", nullable=False),
    )
    op.add_column(
        "events", sa.Column("notify_eligible", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column("events", sa.Column("published_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("events", sa.Column("start_date", sa.Date(), nullable=True))
    op.add_column("events", sa.Column("end_date", sa.Date(), nullable=True))
    op.add_column("events", sa.Column("modality", sa.String(length=30), nullable=True))
    op.add_column("events", sa.Column("population", sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "population")
    op.drop_column("events", "modality")
    op.drop_column("events", "end_date")
    op.drop_column("events", "start_date")
    op.drop_column("events", "published_at")
    op.drop_column("events", "notify_eligible")
    op.drop_column("events", "confidence")
    op.drop_index(op.f("ix_stages_process_id"), table_name="stages")
    op.drop_table("stages")
    op.drop_index(op.f("ix_event_evidence_event_id"), table_name="event_evidence")
    op.drop_table("event_evidence")
    op.drop_index(op.f("ix_changes_process_id"), table_name="changes")
    op.drop_table("changes")
    op.drop_index(op.f("ix_publications_process_id"), table_name="publications")
    op.drop_table("publications")
    # ### end Alembic commands ###
