"""unassigned_publications"""

import sqlalchemy as sa
from alembic import op

revision = "a6d73dc3fd79"
down_revision = "1d986a0ded8f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "publications", "process_id", existing_type=sa.VARCHAR(length=36), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "publications", "process_id", existing_type=sa.VARCHAR(length=36), nullable=False
    )
    # ### end Alembic commands ###
